# Generated by Django 5.1.4 on 2026-06-15 16:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assistant', '0002_alter_chatsession_user_chatsummary_last_message_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chatsession',
            name='chat_type',
            field=models.CharField(choices=[('assistant', 'Assistant'), ('user', 'User'), ('url_analysis', 'URL Analysis')], default='assistant', max_length=20),
        ),
        migrations.CreateModel(
            name='URLAnalysis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField()),
                ('analysis_result', models.JSONField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('session', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='url_analysis', to='assistant.chatsession')),
            ],
        ),
    ]
